project_id = "ofolrzxsowtktgaszwst"

[functions.backfill-history]
verify_jwt = false

[functions.backfill-mecklenburg]
verify_jwt = false

[functions.county-status]
verify_jwt = false

[functions.ingest-county]
verify_jwt = false

[functions.load-zoning]
verify_jwt = false

[functions.parcel-detail]
verify_jwt = true

[functions.parcel-search]
verify_jwt = true

[functions.refresh-views]
verify_jwt = false

[functions.run-until-complete]
verify_jwt = false

[functions.score-county]
verify_jwt = false

[functions.top-parcels]
verify_jwt = true

[functions.vector-tiles]
verify_jwt = true
